# GENERAL SETTINGS
general {
    hide_cursor = false
    ignore_empty_input = true
    fail_timeout = 0
}

# BACKGROUND
background {
    monitor = HDMI-A-1
    path = /home/abys/Pictures/wallpapers/hyprlock.jpg
#    blur_size = 2
#    blur_passes = 2
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
}

# TIME
label {
    monitor = HDMI-A-1
    text = cmd[update:1000] echo "$(date +'%I:%M %p')"
    font_size = 100
    font_family = SF Pro Display Bold
    color = rgb(245, 245, 245)
    halign = right
    valign = top
    position = -50, -20

    shadow_color = rgb(0, 0, 0)
    shadow_size = 5
    shadow_passes = 2
    shadow_boost = 0.2
}

# DATE
label {
    monitor = HDMI-A-1
    text = cmd[update:1000] echo "$(date '+%A, %d %B %Y')"
    font_size = 20
    font_family = SF Pro Display Bold
    color = rgb(245, 245, 245)
    halign = right
    valign = top
    position = -56, -170

    shadow_color = rgb(0, 0, 0)
    shadow_size = 5
    shadow_passes = 2
    shadow_boost = 0.2
}

# ICON
image {
    monitor = HDMI-A-1
    path = /home/abys/.config/pfp.png
    size = 150
    border_size = 0

    shadow_color = rgb(0, 0, 0)
    shadow_size = 5
    shadow_passes = 2
    shadow_boost = 0.4
}

# USER
label {
    monitor = HDMI-A-1
    text = $USER
    font_size = 25
    font_family = Inter Display ExtraBold
    position = 0, -150
}

# INPUT FIELD
input-field {
    monitor = HDMI-A-1
    size = 240, 45
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.4
    dots_center = true
    inner_color = rgba(255, 255, 255, 0.3)
    font_color = rgb(245, 245, 245)
    check_color = rgb(0, 85, 255)
    fade_on_empty = false
    placeholder_text = <span size="13000" font_style="italic" foreground="##ffffffaa"><i>password</i></span>
    hide_input = false
    position = 0, -200
}

# CURRENT SONG
label {
    monitor = HDMI-A-1
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/nowplaying.sh)"
    color = rgba(255,255,255,0.4)
    font_size = 14
    font_family = SF Pro Display
    halign = center
    valign = bottom
    position = 0, 6
}

label {
    monitor = HDMI-A-1
    text = $LAYOUT
    font_size = 14
    font_family = SF Pro Display
    color = rgba(245, 245, 245, 0.3)
    halign = left
    valign = bottom
    position = 6, 6
}
